//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP.net_projekt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MojiResursi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MojiResursi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OOP.net_projekt.Resources.MojiResursi", typeof(MojiResursi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branič.
        /// </summary>
        internal static string branicString {
            get {
                return ResourceManager.GetString("branicString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj golova:.
        /// </summary>
        internal static string goloviLabela {
            get {
                return ResourceManager.GetString("goloviLabela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan.
        /// </summary>
        internal static string kapetanString {
            get {
                return ResourceManager.GetString("kapetanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj žutih  kartona:.
        /// </summary>
        internal static string kartoniLabela {
            get {
                return ResourceManager.GetString("kartoniLabela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muško prvenstvo.
        /// </summary>
        internal static string muskoPrvenstvo {
            get {
                return ResourceManager.GetString("muskoPrvenstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napadač.
        /// </summary>
        internal static string napadacString {
            get {
                return ResourceManager.GetString("napadacString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksimalan broj najdražih igrača je 3..
        /// </summary>
        internal static string porukaZaFlpNajdraziIgrac {
            get {
                return ResourceManager.GetString("porukaZaFlpNajdraziIgrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printanje završeno..
        /// </summary>
        internal static string printanjeZavrsilo {
            get {
                return ResourceManager.GetString("printanjeZavrsilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavanje....
        /// </summary>
        internal static string ucitavanjePoruka {
            get {
                return ResourceManager.GetString("ucitavanjePoruka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaćin:.
        /// </summary>
        internal static string utakmicaUCDomacin {
            get {
                return ResourceManager.GetString("utakmicaUCDomacin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gost:.
        /// </summary>
        internal static string utakmicaUCGost {
            get {
                return ResourceManager.GetString("utakmicaUCGost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija:.
        /// </summary>
        internal static string utakmicaUCLokacija {
            get {
                return ResourceManager.GetString("utakmicaUCLokacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj posjetitelja:.
        /// </summary>
        internal static string utakmicaUCPosjetitelji {
            get {
                return ResourceManager.GetString("utakmicaUCPosjetitelji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veznjak.
        /// </summary>
        internal static string veznjakString {
            get {
                return ResourceManager.GetString("veznjakString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vratar.
        /// </summary>
        internal static string vratarString {
            get {
                return ResourceManager.GetString("vratarString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žensko prvenstvo.
        /// </summary>
        internal static string zenskoPrvenstvo {
            get {
                return ResourceManager.GetString("zenskoPrvenstvo", resourceCulture);
            }
        }
    }
}
