//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Projekt.Resursi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Stringovi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stringovi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_Projekt.Resursi.Stringovi", typeof(Stringovi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalje.
        /// </summary>
        public static string btnDalje {
            get {
                return ResourceManager.GetString("btnDalje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string btnOdustani {
            get {
                return ResourceManager.GetString("btnOdustani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branič.
        /// </summary>
        public static string stringBranic {
            get {
                return ResourceManager.GetString("stringBranic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj igrača:.
        /// </summary>
        public static string stringBrojIgraca {
            get {
                return ResourceManager.GetString("stringBrojIgraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zabijenih golova:.
        /// </summary>
        public static string stringBrojZabijenihGolova {
            get {
                return ResourceManager.GetString("stringBrojZabijenihGolova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj žutih kartona:.
        /// </summary>
        public static string stringBrojZutih {
            get {
                return ResourceManager.GetString("stringBrojZutih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        public static string stringDa {
            get {
                return ResourceManager.GetString("stringDa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izlaz.
        /// </summary>
        public static string stringGumbIzlaz {
            get {
                return ResourceManager.GetString("stringGumbIzlaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muško prvenstvo.
        /// </summary>
        public static string stringGumbMusko {
            get {
                return ResourceManager.GetString("stringGumbMusko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o timu.
        /// </summary>
        public static string stringGumbNajdraziTimInfo {
            get {
                return ResourceManager.GetString("stringGumbNajdraziTimInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string stringGumbPostavke {
            get {
                return ResourceManager.GetString("stringGumbPostavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        public static string stringGumbZatvori {
            get {
                return ResourceManager.GetString("stringGumbZatvori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žensko prvenstvo.
        /// </summary>
        public static string stringGumbZensko {
            get {
                return ResourceManager.GetString("stringGumbZensko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država:.
        /// </summary>
        public static string stringInformacijeReprezentacijaCountry {
            get {
                return ResourceManager.GetString("stringInformacijeReprezentacijaCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gol-razlika:.
        /// </summary>
        public static string stringInformacijeReprezentacijaDifferential {
            get {
                return ResourceManager.GetString("stringInformacijeReprezentacijaDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj neriješenih:.
        /// </summary>
        public static string stringInformacijeReprezentacijaDraws {
            get {
                return ResourceManager.GetString("stringInformacijeReprezentacijaDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFA kod:.
        /// </summary>
        public static string stringInformacijeReprezentacijaFifaCode {
            get {
                return ResourceManager.GetString("stringInformacijeReprezentacijaFifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj odigranih utakmica:.
        /// </summary>
        public static string stringInformacijeReprezentacijaGamesPlayed {
            get {
                return ResourceManager.GetString("stringInformacijeReprezentacijaGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj primljenih golova:.
        /// </summary>
        public static string stringInformacijeReprezentacijaGoalsAgainst {
            get {
                return ResourceManager.GetString("stringInformacijeReprezentacijaGoalsAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zabijenih golova:.
        /// </summary>
        public static string stringInformacijeReprezentacijaGoalsFor {
            get {
                return ResourceManager.GetString("stringInformacijeReprezentacijaGoalsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj poraza:.
        /// </summary>
        public static string stringInformacijeReprezentacijaLoses {
            get {
                return ResourceManager.GetString("stringInformacijeReprezentacijaLoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o reprezentaciji.
        /// </summary>
        public static string stringInformacijeReprezentacijaNaslov {
            get {
                return ResourceManager.GetString("stringInformacijeReprezentacijaNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj pobjeda:.
        /// </summary>
        public static string stringInformacijeReprezentacijaWins {
            get {
                return ResourceManager.GetString("stringInformacijeReprezentacijaWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvaranje aplikacije.
        /// </summary>
        public static string stringIzlazIzAplikacijeNaslov {
            get {
                return ResourceManager.GetString("stringIzlazIzAplikacijeNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan.
        /// </summary>
        public static string stringKapetan {
            get {
                return ResourceManager.GetString("stringKapetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir jezika.
        /// </summary>
        public static string stringLokalizacija {
            get {
                return ResourceManager.GetString("stringLokalizacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najdraži tim.
        /// </summary>
        public static string stringNajdraziTim {
            get {
                return ResourceManager.GetString("stringNajdraziTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napadač.
        /// </summary>
        public static string stringNapadac {
            get {
                return ResourceManager.GetString("stringNapadac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o igraču.
        /// </summary>
        public static string stringNaslovPregledIgraca {
            get {
                return ResourceManager.GetString("stringNaslovPregledIgraca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string stringNe {
            get {
                return ResourceManager.GetString("stringNe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite najdraži tim:.
        /// </summary>
        public static string stringOdaberiNajdraziTim {
            get {
                return ResourceManager.GetString("stringOdaberiNajdraziTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite protivnika:.
        /// </summary>
        public static string stringOdaberiProtivnickiTim {
            get {
                return ResourceManager.GetString("stringOdaberiProtivnickiTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik:.
        /// </summary>
        public static string stringOdabirJezika {
            get {
                return ResourceManager.GetString("stringOdabirJezika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite prvenstvo:.
        /// </summary>
        public static string stringOdabirPrvenstvaLabela {
            get {
                return ResourceManager.GetString("stringOdabirPrvenstvaLabela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir prvenstva.
        /// </summary>
        public static string stringOdabirPrvenstvaNaslov {
            get {
                return ResourceManager.GetString("stringOdabirPrvenstvaNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite preferiranu rezoluciju:.
        /// </summary>
        public static string stringOdabirRezolucijeLabela {
            get {
                return ResourceManager.GetString("stringOdabirRezolucijeLabela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrana rezolucija:.
        /// </summary>
        public static string stringOdabranaRezolucijaLabel {
            get {
                return ResourceManager.GetString("stringOdabranaRezolucijaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrano prvenstvo:.
        /// </summary>
        public static string stringOdabranoPrvenstvoLabel {
            get {
                return ResourceManager.GetString("stringOdabranoPrvenstvoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string stringPotvrdi {
            get {
                return ResourceManager.GetString("stringPotvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija:.
        /// </summary>
        public static string stringPozicija {
            get {
                return ResourceManager.GetString("stringPozicija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protivnički tim.
        /// </summary>
        public static string stringProtivnickiTim {
            get {
                return ResourceManager.GetString("stringProtivnickiTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled prezentacije.
        /// </summary>
        public static string stringReprezentacijaProzorNaslov {
            get {
                return ResourceManager.GetString("stringReprezentacijaProzorNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir rezolucije.
        /// </summary>
        public static string stringRezolucijaNaslov {
            get {
                return ResourceManager.GetString("stringRezolucijaNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Želite li stvarno zatvoriti aplikaciju?.
        /// </summary>
        public static string stringUpit {
            get {
                return ResourceManager.GetString("stringUpit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veznjak.
        /// </summary>
        public static string stringVeznjak {
            get {
                return ResourceManager.GetString("stringVeznjak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vratar.
        /// </summary>
        public static string stringVratar {
            get {
                return ResourceManager.GetString("stringVratar", resourceCulture);
            }
        }
    }
}
